#!/usr/bin/env bash
# the script logs into a server and create a file to "~/"
if [ $# -le 3 ]
   then
	echo Usage: ${0:2} PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
else
	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3"@"$2":~
fi