#!/usr/bin/env bash
# configures a server to rediret a uri and with responce of 301
mv /etc/nginx/sites-enabled/default /etc/nginx/

echo "
     server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;

	index index.html index.htm;

	location /redirect_me {
		return 301 www.google.com;
	}

	location / {
		# FIRST ATTEMPT TO SERVE REQUEST AS FILE, THEN
		# as directory, then fall back to displaying a 404.
		try_files \$uri \$uri/ =404;
	}

}
" > /etc/nginx/sites-enabled/default