#!/usr/bin/env bash
# Installs and configures Nginx on a new Ubuntu machine.
# Configures redirect_me page to redirect to https://www.google.com
# Invalid pages display `Ceci n'est pas une page` and return a 404 status code.

# update machine and install nginx
apt-get update -y
apt-get install nginx -y

# update default html file that comes with nginx
echo "Hello World!" | tee /var/www/html/index.html > /dev/null 2>&1
echo "Ceci n'est pas une page" | tee /var/www/html/error404.html > /dev/null 2>&1

# configure the server block
echo  "server {
      listen 80 default_server;
      listen [::]:80 default_server;

      root /var/www/html;
      index index.html index.htm;

      location /redirect_me {
      	              return 301 https://www.google.com;
      }

      location / {
      	              try_files \$uri \$uri/ =404;
      }

      error_page 404 /error404.html;

      # disable error404.html page for external access
      location = /error404.html {
              root /var/www/html;
      	            internal;
      }
}" > /etc/nginx/sites-available/default

NR=$(grep -n "include /etc/nginx/sites-enabled/*" /etc/nginx/nginx.conf | cut -d ":" -f 1)
NR=$((NR+1))

grep "X-Served-By" /etc/nginx/nginx.conf > temp_file

if [ "$(cat < temp_file | wc -c)" = 0 ]; then
    sed -e "${NR}i\\" -e '\tadd_header X-Served-By \"$hostname\";' \
	/etc/nginx/nginx.conf > temp_file
    mv temp_file /etc/nginx/nginx.conf
else
    rm temp_file
fi

# restart nginx
service nginx restart