#!/usr/bin/env bash
# Installs and configures HAProxy.

apt update -y

# install haproxy
apt install haproxy -y

# Enable HAProxy to start by init script
printf "\nENABLED=1\n" >> /etc/default/haproxy

printf "\n
       frontend myfrontend
       		bind :80
		default_backend webservers

       backend webservers
       	       balance roundrobin
       	       server 208053-web-01 18.210.33.133
	       server 208053-web-02 35.174.200.184
\n" >> /etc/haproxy/haproxy.cfg

service haproxy restart
