#!/usr/bin/env bash
# This script:
# Creates the file /var/run/myscript.pid to store its PID
# Displays "To infinity and beyond" indefinitely
# Displays "I hate the kill command" when receiving a SIGTERM signal
# Displays "Y U no love me?!" when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a
#+ SIGQUIT or SIGTERM signal


PID_FILE="/var/run/myscript.pid"

echo "$$" > "$PID_FILE"

exit_prog() {
   rm "$PID_FILE"
   exit
}

while true; do
     echo "To infinity and beyond"
     sleep 2
     trap "echo Y U no love me?!" SIGINT
     trap "echo I hate kill command && exit_prog" SIGTERM
     trap exit_prog SIGQUIT
done
