#!/usr/bin/env bash
# this script takes an argument and runs the following
# When passing the argument start:
  # Starts manage_my_process
  # Creates a file containing its PID in /var/run/my_process.pid
  # Displays manage_my_process started
# When passing the argument stop:
  # Stops manage_my_process
  # Deletes the file /var/run/my_process.pid
  # Displays manage_my_process stopped
# When passing the argument restart
  # Stops manage_my_process
  # Deletes the file /var/run/my_process.pid
  # Starts manage_my_process
  # Creates a file containing its PID in /var/run/my_process.pid
  # Displays manage_my_process restarted
# Displays Usage: manage_my_process {start|stop|restart} on other cases

PID_FILE="/var/run/my_process.pid"
PROCESS_FILE="manage_my_process"

case "$1" in
     "start")
	./$PROCESS_FILE &
	 echo $$ > $PID_FILE
	 echo "manage_my_process started"
	 exit 0
	 ;;
        "stop")
	 pkill -f /manage_my_process
	 rm $PID_FILE
	 echo "manage_my_process stopped"
	 exit 0
	 ;;
        "restart")
	 pkill -f /$PROCESS_FILE
	 rm $PID_FILE
	 ./$PROCESS_FILE &
	 echo $$ > $PID_FILE
	 echo "manage_my_process restarted"
         exit 0
	 ;;
        *)
          echo $"Usage: ${0:6} {start|stop|restart}"
          exit 1
esac