#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd:
# script only display:
# username
# user id
# Home directory path for the user

file="/etc/passwd"
while read -r line;
do
    echo -e "$line" | cut -d: -f1,4,6;
done < $file
exit 0
