#!/usr/bin/env bash
# this script
# changes facebook IP and Local host IP in the Host file
cp /etc/hosts /etc/host.new
sed -i 's/127.0.0.1/127.0.0.2/g; s/157.240.11.35/8.8.8.8/g' /etc/host.new
cat /etc/host.new > /etc/hosts
