#!/usr/bin/env bash
# Run nginx as user `nginx` on port 8080.
chmod 644 /etc/nginx/nginx.conf
sed -i 's.80.8080.g' /etc/nginx/sites-available/default
kill "$(pgrep apache2 | head -1)"
su nginx -c "service nginx start"

